### ISSUE TITLE
human readable names

### ISSUE THREAD

**Issue by QiXi** [greymag/tinkoff-invest-openapi-dart-sdk#1]
Было бы удобнее видеть название полей 'open', 'close' вместо 'o', 'c' итд.

https://github.com/greymag/tinkoff-invest-openapi-dart-sdk/blob/d230e98c00fb6cc94f8b73929c68e0f99418cfe4/lib/src/models/data/candle.dart#L15

**Comment by greymag** [comment]
Сами названия полей соответствуют моделям в API, думаю не стоит их менять, чтобы не создавать неоднозначности. Но можно добавить геттеры с более понятными именами, возможно это будет удобно.
