### ISSUE TITLE
Ошибочный комментарий

### ISSUE THREAD

**Issue by QiXi** [greymag/tinkoff-invest-openapi-dart-sdk#3]
https://github.com/greymag/tinkoff-invest-openapi-dart-sdk/blob/6d15a40663ba0f17a9f316c274b6a40398f41c17/lib/src/endpoints/ti_user_endpoint.dart#L12

Комментарий не соответствует действительности.
И ещё, если открыто два счета, но метод возвращает только один, то проблема в реализации или на стороне брокера?

**Comment by greymag** [comment]
>Комментарий не соответствует действительности.

Спасибо, поправил 

> И ещё, если открыто два счета, но метод возвращает только один, то проблема в реализации или на стороне брокера?

У меня ИИС и Брокерский - приходят оба. Несколько брокерских не пробовал. 

Передайте флаг `debug` при создании экземпляра `TinkoffInvestApi` - будут распечатаны все запросы и ответы, сможете посмотреть что приходит от API. Если там есть данные счета, а реализация возвращает 1 - значит баг в реализации, если же API возвращает 1 - значит проблема на стороне брокера. 

Отпишите, пожалуйста, о результате.

**Comment by QiXi** [comment]
Я уже по-всякому проверил. Долго искал откуда берется `brokerAccountId`, но в итоге вычислил что это номер договора. Если подставлять насильно самый первый открытый `brokerAccountId`, то все работает. А если подставлять второй открытый номер счета, которого также нет в списке `accounts()`, то не работает. Собственно в документации тоже написано что 

> Поддерживаются ли сейчас мультисчета в openAPI?
> Поддержка мультисчетов в openAPI в процессе разработки. Работаем над этим.

**Comment by greymag** [comment]
Понятно, жаль. Будем ждать выполнения https://github.com/TinkoffCreditSystems/invest-openapi/issues/533
