### ISSUE TITLE
Сложности при работе с PlacedLimitOrder и PlacedMarketOrder

### ISSUE THREAD

**Issue by QiXi** [greymag/tinkoff-invest-openapi-dart-sdk#6]
В данной реализации типы данных PlacedLimitOrder и PlacedMarketOrder разнесены по двум раздельным классам, хотя содержимое один в один совпадает. Это вызывает сложность, например, если есть потребность поместить их в единую типизированную коллекцию и комфортно работать без приведения типов.

Предлагаемые вырианты решения:
1) Оставить один тип данных и добавить признак ордера.
2) Унаследовать одно от другого.
3) Унаследовать от единого интерфейса.

Хотелось бы услышать причины разнесения этих ответов на несвязанные между собой типы и на сколько предложение №1 или №3 целесообразны.

**Comment by greymag** [comment]
Согласен, при реализации меня тоже это смущало, но решил сделать как было в [API](https://tinkoffcreditsystems.github.io/invest-openapi/swagger-ui/), чтобы не нарушать консистентность реализации.

Думаю вариант с интерфейсом/базовым классом имеет право на существование, по крайней мере до тех пор, пока они остаются совместимыми с точки зрения API. 

Сделаю в ближайшее время.

**Comment by greymag** [comment]
Добавил в [v0.1.2](https://pub.dev/packages/tinkoff_invest/versions/0.1.2)
