### ISSUE TITLE
productionRestUrl 

### ISSUE THREAD

**Issue by jodaka** [greymag/tinkoff-invest-openapi-dart-sdk#7]
Я попробовал сделать новое приложение и получить состояние портфеля, но получаю ошибку 
```
*** DioError ***:
uri: https://api-invest.tinkoff.ru/openapi/portfolio
DioError [DioErrorType.response]: Http status error [403]
uri: https://api-invest.tinkoff.ru/openapi/portfolio
statusCode: 403
```
токен свежеполученный. Заметил, что URL отличается от того, что указан в документации (https://tinkoff.github.io/investAPI/). 
```
Все вызовы продового сервиса выполняются по адресу invest-public-api.tinkoff.ru:443.

Все вызовы сервиса песочницы выполняются по адресу sandbox-invest-public-api.tinkoff.ru:443.
```
403 ошибка может быть результатом того, что поменялся URL для доступа к данным?

**Comment by greymag** [comment]
Добрый день. 

403 - это "доступ запрещен", т.е. нет прав на доступ к указанному URL. Да, может быть в том числе потому что теперь адрес для API другой.

SDK была написана под предыдущую версию API, с тех пор вышла новая версия и, вероятно, старая теперь уже недоступна. 

Я не смотрел новую версию, т.к. отпала необходимость взаимодействия с API Tinkoff.

**Comment by jodaka** [comment]
Понял, спасибо! 
Попробую на досуге поковыряться и адаптировать к новой версии.
